apiVersion: v1
kind: PersistentVolume
metadata:
  name: orchestrator-database-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/nfs/pvdborch
    server: 90.147.170.162
