apiVersion: v1
kind: Service
metadata: 
  labels: 
    service: orchestrator
    component: backend    
  name: orchestrator
spec: 
  ports:
    - port: 8080
  selector: 
    service: orchestrator
    component: backend
  type: LoadBalancer
