apiVersion: v1
kind: PersistentVolume
metadata:
  name: orchestrator-pv
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/nfs/pvorch
    server: 90.147.170.162
